### ISSUE TITLE
spring-integration-smb 1.1 does not work with spring integration 5.2.

### ISSUE THREAD

**Issue by zbabos** [spring-projects/spring-integration-extensions#221]
Hi,
at the moment spring-integration-smb 1.1 does not work with spring integration 5.2.
For instance SmbSession does not implement String getHostPort(); abstract method of 5.2 version Session.class.

The spring-integration-smb 1.2  is not yet available in Maven Repository, but I have seen its SmbSession source also does not implement this String getHostPort()  yet.

Are there any plans for an update?

regards
Zoltan BABOS

**Comment by GregBragg** [comment]
I believe the intention from a release perspective was to release spring-integration-smb 1.2 when spring integration 5.2 went GA, however I'll let @artembilan speak to that plan.

@artembilan We should also consider upgrading the dependent JCIF library to the latest version in the Gradle build before building against Spring Integration 5.2.

Thanks.

**Comment by artembilan** [comment]
I have just pushed upgrades: https://github.com/spring-projects/spring-integration-extensions/commit/442463ad8fa944f48cd786387bf2c4ae2dd5a499

Ping me, please, next week, somewhere on Tuesday, so I don't forget to release it 😉

**Comment by artembilan** [comment]
Fixed via: https://github.com/spring-projects/spring-integration-extensions/commit/ad3374648eeb73722edb9db71431094af2300dc3

Here is a release: https://repo.spring.io/release/org/springframework/integration/spring-integration-smb/1.2.0.RELEASE/.

On its way to Maven Central.
